package app.aaps.plugins.aps.openAPSAIMI.advisor

import app.aaps.plugins.aps.openAPSAIMI.advisor.oref.OrefAnalysisReport
import app.aaps.plugins.aps.openAPSAIMI.patient.HarmoniaDecision

/**
 * =============================================================================
 * AIMI ADVISOR DATA MODELS
 * =============================================================================
 * 
 * Simple, non-nullable data classes for the AIMI Profile Advisor feature.
 * Zero external dependencies - guaranteed crash-free.
 * =============================================================================
 */

/**
 * Metrics collected for analysis.
 */
data class AdvisorMetrics(
    val periodLabel: String,
    val tir70_180: Double,          // Fraction (0-1)
    val tir70_140: Double,
    val timeBelow70: Double,
    val timeBelow54: Double,
    val timeAbove180: Double,
    val timeAbove250: Double,
    val meanBg: Double,             // mg/dL
    val variabilityCv: Double,      // fraction (0-1), CV = sd / mean
    val gmi: Double,                // % (derived)
    val tdd: Double,                // U/day
    val basalPercent: Double,       // Basal as fraction of TDD
    val hypoEvents: Int,
    val severeHypoEvents: Int,
    val hyperEvents: Int,
    val todayTir: Double?,    // (0-1) or null
    val todayTdd: Double?     // U or null
)

/**
 * Severity classification for the overall score.
 */
sealed class AdvisorSeverity {
    object Good : AdvisorSeverity()
    object Warning : AdvisorSeverity()
    object Critical : AdvisorSeverity()
}

/**
 * 🧩 AdvisorActionStrategy
 *
 * Defines the contract for all actionable recommendations generated by the AIMI Advisor.
 * This strategy pattern allows for decoupled validation, execution, and persistence
 * of profile adjustments (e.g., updating ISF, Basal, or SMB thresholds).
 */
interface AdvisorActionStrategy {
    /**
     * Performs a clinical safety check before the action is presented to the user.
     * @return True if the proposed change is within physiological safety bounds.
     */
    fun validate(): Boolean

    /**
     * Executes the action, typically by updating the underlying [Preferences] or [PersistenceLayer].
     */
    fun apply()

    /**
     * Converts the action into a human-readable and machine-parsable string for auditing.
     * @return A serialized representation of the action.
     */
    fun serialize(): String
}

/**
 * A single recommendation from the advisor.
 * Uses Resource IDs for localization.
 */
data class AimiRecommendation(
    val titleResId: Int,
    val descriptionResId: Int,
    val priority: app.aaps.plugins.aps.openAPSAIMI.model.AimiPriority,
    val domain: app.aaps.plugins.aps.openAPSAIMI.model.AimiDomain,
    val action: app.aaps.plugins.aps.openAPSAIMI.model.AimiAction? = null,
    val descriptionArgs: List<String> = emptyList() // For dynamic description formatting
)

/**
 * Full advisor report.
 */
data class AdvisorReport(
    val generatedAt: Long,
    val metrics: AdvisorMetrics,
    val overallScore: Double,           // 0-10 score
    val overallSeverity: AdvisorSeverity,
    val overallAssessment: String,
    val recommendations: List<AimiRecommendation>,
    // PkpdSuggestions merged into recommendations with Domain.PKPD
    val summary: String,
    /** Same snapshot as used to build this report (avoid duplicate collectContext / heavy DB work). */
    val advisorContext: AdvisorContext,
    /** On-device OREF-aligned feature/outcome analysis (local DB); LGBM scores optional via ONNX. */
    val orefAnalysis: OrefAnalysisReport? = null,
    /** Latest Harmonia simulation branch attached to the runtime, sandbox-only. */
    val harmoniaDecision: HarmoniaDecision? = null,
)

/**
 * =============================================================================
 * RULES ENGINE MODELS
 * =============================================================================
 */


data class AdvisorContext(
    val metrics: AdvisorMetrics,
    val profile: AimiProfileSnapshot,
    val prefs: AimiPrefsSnapshot,
    val pkpdPrefs: PkpdPrefsSnapshot,
    val harmoniaDecision: HarmoniaDecision? = null,
)

data class AimiProfileSnapshot(
    val nightBasal: Double,      // U/h (average or specific block)
    val icRatio: Double,         // g/U (weighted average)
    val isf: Double,             // mg/dL/U (weighted average)
    val targetBg: Double,        // mg/dL (weighted average)
    val dia: Double,             // hours
    val totalBasal: Double       // U/day (sum of profile basal)
)

data class AimiPrefsSnapshot(
    val maxSmb: Double,                     // U
    val lunchFactor: Double,                // multiplier
    val unifiedReactivityFactor: Double,    // multiplier
    val autodriveMaxBasal: Double,          // U/h
    val autodriveEnabled: Boolean = false,
    /** Autodrive MPC-style aggressiveness (insulin per kg per 5 min step). */
    val mpcInsulinUPerKgPerStep: Double = 0.065,
)

data class AdvisorFlag(
    val code: String,
    val severity: AdvisorSeverity
)

/**
 * =============================================================================
 * PKPD MODELS
 * =============================================================================
 */

data class PkpdPrefsSnapshot(
    val pkpdEnabled: Boolean,
    val initialDiaH: Double,
    val initialPeakMin: Double,
    val boundsDiaMinH: Double,
    val boundsDiaMaxH: Double,
    val boundsPeakMinMin: Double,
    val boundsPeakMinMax: Double,
    val maxDiaChangePerDayH: Double,
    val maxPeakChangePerDayMin: Double,
    val isfFusionMinFactor: Double,
    val isfFusionMaxFactor: Double,
    val isfFusionMaxChangePerTick: Double,
    val smbTailThreshold: Double,
    val smbTailDamping: Double,
    val smbExerciseDamping: Double,
    val smbLateFatDamping: Double
)
