package app.aaps.plugins.aps.openAPSAIMI.recursive

/**
 * Optional tick-local signals for full §15 leaf coverage — assembled once per RBT resolve.
 */
data class RbtExtendedSignals(
    val tubeAdvisorCapScale: Double? = null,
    val insulinActivityStageOrdinal: Int? = null,
    val pkpdTailFactor: Double? = null,
    val compressionImpossibleRise: Boolean = false,
    val decisionModulationFactor: Double? = null,
    val highBgOverrideActive: Boolean = false,
    val iobConsensusDelta: Double? = null,
    val realtimeIobUnits: Double? = null,
    val mealAdvisorEstimateU: Double? = null,
    val mpcFeedForwardRa: Double? = null,
    val cbfShieldDeltaU: Double? = null,
    val t3cAnticipationStrength: Double? = null,
    val t3cActive: Boolean = false,
    val t3cBasalDemandRateUph: Double? = null,
    val t3cBasalMaxRateUph: Double? = null,
    val t3cMealConflict: Boolean = false,
    val t3cPostHypoBlock: Boolean = false,
    val t3cExerciseBlock: Boolean = false,
    val t3cHardSafetyBlock: Boolean = false,
    val t3cBlockReason: String? = null,
    val t3cGovernanceBasalFloorUph: Double? = null,
    val t3cGovernanceAggressivenessFloor: Double? = null,
    val harmoniaActive: Boolean = false,
    val harmoniaDecisionEligible: Boolean = false,
    val harmoniaAction: String? = null,
    val harmoniaBranch: String? = null,
    val harmoniaBasalDemandRateUph: Double? = null,
    val harmoniaBasalMaxRateUph: Double? = null,
    val harmoniaSmbDemandU: Double? = null,
    val harmoniaSmbMaxU: Double? = null,
    val harmoniaMealConflict: Boolean = false,
    val harmoniaPostHypoBlock: Boolean = false,
    val harmoniaExerciseBlock: Boolean = false,
    val harmoniaHardSafetyBlock: Boolean = false,
    val harmoniaBlockReason: String? = null,
    /** Tree-deployed insulin intent for Harmonia SMB arbitration. */
    val insulinIntent: String? = null,
    /** MealCertainty MED/HIGH — required for soft-cap LIFT. */
    val mealCertaintySupports: Boolean = false,
    /** Confirmed rise geometry for soft meal escalation. */
    val riseConfirmed: Boolean = false,
    /** [PostHypoDeliveryAuthority] requests zero SMB on the RBT channel. */
    val postHypoDeliverySuppressSmb: Boolean = false,
    val postHypoOrdinal: Int? = null,
    val trajSpiralCapMaxSmb: Double? = null,
    val pkpdLearnedDiaH: Double? = null,
    val pkpdLearnedPeakMin: Double? = null,
    val isfFusionRatio: Double? = null,
    val kalmanIsf: Double? = null,
    val kalmanIsfTrust: Double? = null,
    val peakBiasMinutes: Int? = null,
    val peakMismatchScore: Double? = null,
    val pkpdTailDamping: Double? = null,
    val correctionAggressionLevel: Double? = null,
    val hormonalCapApplied: Boolean = false,
    val ngrSmbMult: Double? = null,
    val ngrBasalMult: Double? = null,
    val inflammationSmbMult: Double? = null,
    val inflammationIsfMult: Double? = null,
    val basalAdaptMult: Double? = null,
    val dynBasalFactor: Double? = null,
    val ctxManagerIntentCount: Int = 0,
    val endometriosisFactor: Double? = null,
    val thyroidIsfMult: Double? = null,
    val thyroidDiaMult: Double? = null,
    val thyroidGuardActive: Boolean = false,
    val gestationBasalMult: Double? = null,
    val basalLearnerShortMult: Double? = null,
    val basalLearnerMedMult: Double? = null,
    val basalLearnerLongMult: Double? = null,
    val onlineLearnFactor: Double? = null,
    val attentionGateScore: Double? = null,
    val dynIsfTrajFactor: Double? = null,
    val stackingEventualDrop: Double? = null,
    val stackingMinPredDrop: Double? = null,
    val htrLeafSmbFloorU: Double? = null,
    val shadowComparatorDeltaU: Double? = null,
    val shadowVirtualBgMgdl: Double? = null,
    val shadowAuditorConfidence: Double? = null,
    val shadowSentinelVerdictLabel: String? = null,
    val shadowOrchestratorActive: Boolean = false,
    val shadowVisionTriggered: Boolean = false,
    val shadowMlTrainActive: Boolean = false,
    val tuningContextLabel: String? = null,
    val sleepDebtMinutes: Double? = null,
    val latentMealProb: Double? = null,
    val latentEndogenousGlucoseDrive: Double? = null,
    val latentCircadianSiFactor: Double? = null,
    val latentTransientResistanceProb: Double? = null,
    val latentSleepDebtScore: Double? = null,
    val latentSensorConfidence: Double? = null,
    val uamHypothesisDominant: String? = null,
    val uamMealProb: Double? = null,
    val uamEndogenousProb: Double? = null,
    val uamStressProb: Double? = null,
    val uamPostHypoProb: Double? = null,
    val uamLateFatProb: Double? = null,
    val uamSuppressMealInterpretation: Boolean = false,
    val patientMode: String? = null,
    val patientModeConfidence: Double? = null,
    val patientStrategyHint: String? = null,
    val patientModeMealBias: Double? = null,
    val patientModeProtectionBias: Double? = null,
    val causalDominantState: String? = null,
    val causalDominantConfidence: Double? = null,
    val causalMealConfidence: Double? = null,
    val causalProtectiveConfidence: Double? = null,
    val causalLearningQuality: Double? = null,
    val contextIntentDominant: String? = null,
    val contextIntentConfidence: Double? = null,
    val physioMtrStateOrdinal: Int? = null,
    val hrvDeviationZ: Double? = null,
    val sleepQualityScore: Double? = null,
    val sleepLiveConfidence: Double? = null,
    val sleepLiveSource: String? = null,
) {
    companion object {
        val EMPTY = RbtExtendedSignals()
    }
}
