name: Sync Upstream and Build (master)

on:
  workflow_dispatch: # Ermöglicht das manuelle Starten im "Actions"-Tab
  #schedule:
    # Läuft alle 6 Stunden (um 0, 6, 12, 18 Uhr UTC)
  #  - cron: '0 3 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          # Dies ist der Branch in *deinem* Fork, den du aktualisieren möchtest
          ref: master
          # Wir verwenden das PAT, damit der Push den Build-Workflow auslösen kann
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions Sync'
          git config --global user.email 'actions@github.com'

      - name: Add Upstream Remote
        run: |
          # Dies ist das *Original*-Repo, von dem du geforkt hast
          git remote add upstream https://github.com/MTR93600/OpenApsAIMI.git

      - name: Fetch and Rebase from Upstream
        run: |
          git fetch upstream
          # Dies ist die 'rebase'-Strategie, sie ist sauberer als 'merge'.
          # Sie nimmt deine Commits (z.B. an dieser .yml-Datei) 
          # und spielt sie auf dem neuesten Stand von upstream/master ab.
          git rebase upstream/master

      - name: Push Changes (Force)
        run: |
          # Nach einem 'rebase' ist ein 'force push' notwendig.
          # Da dies dein persönlicher Fork ist, ist das sicher.
          # Dieser Push löst deinen 'Android Build (Signed)' Workflow aus.
          git push origin master --force
